# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Note: ip address must match ip address used in ansible/local.yml
  private_ip = "192.168.33.11"
  config.vm.box = "centos8-devbox"

  # Create a private network
  config.vm.network "private_network", ip: private_ip

  # Web server
  config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.network :forwarded_port, guest: 443, host: 443

  # Java apps
  config.vm.network :forwarded_port, guest: 5005, host: 5005
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 8443, host: 8443

  # Oracle Net Listener port
  config.vm.network :forwarded_port, guest: 1521, host: 1521

  # Docker daemon
  config.vm.network :forwarded_port, guest: 2375, host: 2375

  # Kubernetes API (via kubectl proxy)
  config.vm.network :forwarded_port, guest: 8001, host: 8001

  # Minio S3 API
  config.vm.network :forwarded_port, guest: 9000, host: 9000

  # CNTLM proxy
  config.vm.network :forwarded_port, guest: 3128, host: 3128

  # X11 forwarding
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  # VirtualBox provider configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "CentOS 8 Devbox"
    vb.memory = "10240"
    vb.cpus = 2
  end

  # Mount projects folder
#  config.vm.synced_folder "D:/projects", "/home/vagrant/projects",
#    owner: "vagrant",
#    group: "vagrant",
#    mount_options: ["dmode=775,fmode=664"]

  # Mount /ansible folder (read-only for world)
#  config.vm.synced_folder "ansible", "/ansible",
#    owner: "vagrant",
#    group: "vagrant",
#    mount_options: ["dmode=775,fmode=664"]

  # Perform Ansible provisioning
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "devbox.yml"
    ansible.config_file = "ansible.cfg"
    ansible.provisioning_path = "/vagrant/ansible"
  end

end
